# Generated by Django 3.1.14 on 2022-09-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubApp', '0003_auto_20211101_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={},
        ),
    ]
